services:
    WvisionBundle\Installer\AssetsInstaller:
        arguments:
            - '@kernel'
            - '@filesystem'

    WvisionBundle\Installer\DemoInstaller:
        arguments:
            - '@doctrine.dbal.default_connection'
