services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WvisionBundle\Tool\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('CoreShopAdminBundle')"
        calls:
            - [setFileSystem, ['@filesystem']]
            - [setInstaller, ['@WvisionBundle\Installer\CompositeResourceInstaller']]