services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WvisionBundle\Installer\BundleInstaller:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('WvisionBundle')"
        calls:
            - [setDemoInstaller, ['@WvisionBundle\Installer\DemoInstaller']]
            - [setAssetsInstaller, ['@WvisionBundle\Installer\AssetsInstaller']]