services:
    # Mailer
    WvisionBundle\Tool\Mailer:
        class: WvisionBundle\Tool\Mailer
        arguments:
            - '@pimcore.service.request.document_resolver'

    # iCalendar
    WvisionBundle\Tool\Ics:
        class: WvisionBundle\Tool\Ics