services:

    # tool: installer
    WvisionBundle\Tool\Installer:
        class: WvisionBundle\Tool\Installer
        arguments:
            - '@logger'
            - '@pimcore_admin.serializer'
        tags:
            - { name: monolog.logger }

    # tool: mailer
    WvisionBundle\Tool\Mailer:
        class: WvisionBundle\Tool\Mailer
#        autowire: true