imports:
  - { resource: services/*.yml }

services:

  # configuration
  WvisionBundle\Configuration\Configuration:
    class: WvisionBundle\Configuration\Configuration
    arguments:
      - '@pimcore.extension.bundle_manager'
