framework:
  assets:
    json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'

twig:
  globals:
    kernelPublicDir: '%kernel.project_dir%/web/'
  form_themes:
    - 'Form/uikit_3_layout.html.twig'