wvision.admin.settings.get_settings:
  path: /admin/wvision/settings/get-settings
  defaults: { _controller: WvisionBundle:Admin\Settings:getSettings }

wvision.admin.settings.get:
  path: /admin/wvision/settings/get
  defaults: { _controller: WvisionBundle:Admin\Settings:get }

wvision.admin.settings.set:
  path: /admin/wvision/settings/set
  defaults: { _controller: WvisionBundle:Admin\Settings:set }

wvision.admin.newsletter.send:
  path: /admin/wvision/newsletter/send
  defaults: { _controller: WvisionBundle:Admin\Newsletter:send }

wvision.admin.newsletter.send-test:
  path: /admin/wvision/newsletter/send-test
  defaults: { _controller: WvisionBundle:Admin\Newsletter:sendTest }